# Generated by Django 4.2.16 on 2025-06-29 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_person_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
